<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>orca/integer basic with support for "named_lines"</string>
	<key>fileTypes</key>
	<array>
		<string>bas</string>
	</array>
	<key>name</key>
	<string>MPW Integer BASIC</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*"([A-Za-z0-9_~]+)"</string>
			<key>name</key>
			<string>meta.function.definition</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*\d+</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(?i:call)\s+([A-Za-z0-9_~]+)</string>
			<key>name</key>
			<string>meta.function.call</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:rem)\b.*$</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\d+</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:CALL|END|FOR|GOSUB|GOTO|IF|NEXT|POP|RETURN|STEP|THEN|TO)\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:DIM|LET)\b</string>
			<key>name</key>
			<string>keyword.variable</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:INPUT|PRINT|TAB|TEXT|TEXT80|VTAB)\b</string>
			<key>name</key>
			<string>keyword.io</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:ABS|RND|SGN)\b</string>
			<key>name</key>
			<string>support.function.arithmetic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:ASC|LEN)\b</string>
			<key>name</key>
			<string>support.function.string</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:AT|COLOR|GR|HGR|HLIN|PLOT|VLIN)\b</string>
			<key>name</key>
			<string>keyword.graphics</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:SCRN)\b</string>
			<key>name</key>
			<string>support.function.graphics</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:PDL)\b</string>
			<key>name</key>
			<string>support.function.io</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:AND|OR|NOT)\b</string>
			<key>name</key>
			<string>keyword.operator.logical</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:MOD)\b</string>
			<key>name</key>
			<string>keyword.operator.mathematical</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[A-Za-z][A-Za-z0-9]*\$?</string>
			<key>name</key>
			<string>variable</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.integer-basic.mpw</string>
	<key>uuid</key>
	<string>2D210058-A6F9-4C73-9832-415914D6C1D4</string>
</dict>
</plist>
